# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Allow longer lines and methods in test files
Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/*.rake'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
